// import 'package:mymoney/main.dart';
// import 'package:mymoney/res/allSharePreferencesKey.dart';

// clearAllSharePrefrerenceValue() {
//   sharedPreferences!.setString(AllSharedPreferencesKey.companyId, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.companyName, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.companyContactNo, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.companyEmailId, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.companyAddress, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.district, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.companyPincode, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.userId, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.firstName, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.branchName, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.branchId, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.individualTypeId, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.image, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.userType, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.token, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.punchInId, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.breakPunchId, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.address, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.allProductJson, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.location, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.latitude, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.longitude, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.allCategoryJson, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.allExpenseTypeJson, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.allDealerJson, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.productList, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.contact1, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.contact2, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.dob, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.email, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.checkInOption, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.checkInOptionName, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.checkInId, "");
//   sharedPreferences!
//       .setString(AllSharedPreferencesKey.checkInOptionNameWithId, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.colorPrimary, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.colorPrimaryDark, "");
//   sharedPreferences!.setString(AllSharedPreferencesKey.colorAccent, "");
// }
